// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdsvnvynqrkuqpjdathj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhkc3ZudnlucXJrdXFwamRhdGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMDg5OTAsImV4cCI6MjA1NTU4NDk5MH0.SPwd6UMuPayyAsIBsJ7P9-3sEX52SWXJnafBgydgGZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);